name: Heart of Clojure
url: https://2024.heartofclojure.eu
cfp_url: https://cfp.heartofclojure.eu/events/heart-of-clojure
tickets_url: https://ti.to/heart-of-clojure/heart-of-clojure-2019-leuven-belgium
tickets_enabled: false
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
classsets:
  button_non_white_bg: "link ba br2 bw2 f4 b--white hover-bg-white hover-pink-t60 b white pv3 ph4 mh3"
plugins:
  - jekyll-redirect-from
sections:
  cfp: false
  speakers: true
collections:
  talks:
    output: true
defaults:
  - scope:
      path: ""
    values:
      title: "Heart of Clojure"
      description: "Two days filled with talks, workshops, and activities. September 18 & 19, Leuven, Belgium."
      site_name: heartofclojure.eu
      url: https://2024.heartofclojure.eu
      image: /img/opengraph.png
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
      permalink: "/talks/:title/"
