version: '3'
services:
  hoc:
    image: jekyll/jekyll
    container_name: hoc
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle:Z
    command: "jekyll serve"
